# RestorePoint Demo
# Provision and Deploy a simple HTML web application

trigger: none

pool: Default

stages:
- stage: provisionAKS
  displayName: Provision an AKS cluster
  jobs:
    - job: provision
      displayName: Provision AKS cluster
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'

      - script: terraform init
        displayName: Terraform Initialization
      
      - script: terraform plan
        displayName: Terraform Plan

- stage: deployApp
  displayName: Deploy Nginx deployment
  dependsOn: provisionAKS
  jobs:
    - job: deploy
      displayName: Deploy Manifest files
      steps:
        - task: KubectlInstaller@0
          inputs:
            kubectlVersion: 'latest'