# RestorePoint Demo
# Provision and Deploy a simple HTML web application

trigger: none

pool: Default

variables:
- group: RestorePoint-Demo

stages:
- stage: provisionAKS
  displayName: Provision an AKS cluster
  jobs:
    - job: provision
      displayName: Provision AKS cluster
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
      
      - task: replacetokens@5
        inputs:
          targetFiles: '**/*.tf'
          encoding: 'auto'
          tokenPattern: 'azpipelines'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform init
        displayName: Terraform Initialization
      
      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform plan
        displayName: Terraform Plan

- stage: deployApp
  displayName: Deploy Nginx deployment
  dependsOn: provisionAKS
  jobs:
    - job: deploy
      displayName: Deploy Manifest files
      steps:
        - task: KubectlInstaller@0
          inputs:
            kubectlVersion: 'latest'