# RestorePoint Demo
# Provision and Deploy a simple HTML web application

trigger: none

pool: Default

variables:
- group: RestorePoint-Demo

stages:
- stage: terraformDestroy
  displayName: Destroy the AKS cluster
  condition: eq(variables.terraformDestroy, 'true')
  jobs:
    - job: destroy
      displayName: Destroy the AKS cluster
      steps:
      - task: replacetokens@5
        inputs:
          targetFiles: '**/*.tf'
          encoding: 'auto'
          tokenPattern: 'azpipelines'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true
        displayName: Replace Tokens

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform init
        displayName: Terraform Initialization

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform destroy -auto-approve
        displayName: Terraform Destroy

- stage: provisionAKS
  displayName: Provision an AKS cluster
  dependsOn: terraformDestroy
  jobs:
    - job: terraformPlan
      displayName: Terraform Plan for the AKS cluster
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
        displayName: Install Terraform
      
      - task: replacetokens@5
        inputs:
          targetFiles: '**/*.tf'
          encoding: 'auto'
          tokenPattern: 'azpipelines'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true
        displayName: Replace Tokens

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform init
        displayName: Terraform Initialization
      
      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform plan -out=plan.out
        displayName: Terraform Plan
      
      - task: CopyFiles@2
        inputs:
          contents: '$(System.DefaultWorkingDirectory)/Terraform/plan.out'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: Copy Terraform Plan file

      - publish: '$(Build.ArtifactStagingDirectory)/Terraform/plan.out'
        artifact: terraformPlan
        displayName: Publish Terraform Plan file

    - job: waitForValidation
      displayName: Manual Validation
      pool: server
      dependsOn: terraformPlan
      steps:   
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: 'abdullah.safi44@gmail.com'
          instructions: 'Please validate the Terraform Plan'
        displayName: Wait for external validation

    - job: terraformApply
      displayName: Provision the AKS cluster
      dependsOn: waitForValidation
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
        displayName: Install Terraform

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'terraformPlan'
          targetPath: '$(System.DefaultWorkingDirectory)/Terraform'
        displayName: Download Terraform Plan file

      - task: replacetokens@5
        inputs:
          targetFiles: '**/*.tf'
          encoding: 'auto'
          tokenPattern: 'azpipelines'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true
        displayName: Replace Tokens

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform init
        displayName: Terraform Initialization

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform apply plan.out
        displayName: Terraform Apply

- stage: deployApp
  displayName: Deploy Nginx deployment
  dependsOn: provisionAKS
  jobs:
    - job: deploy
      displayName: Deploy Manifest file
      steps:
      - task: KubectlInstaller@0
        inputs:
          kubectlVersion: 'latest'
        displayName: Install Kubectl

      - script: |
          az account set --subscription $(subscription_id)
          az aks get-credentials --resource-group $(aks_rg_name) --name $(aks_cluster_name)
          kubectl get nodes
        displayName: Connect to the AKS cluster

      - script: Kubectl apply -f Manifest/nginx.yaml
        displayName: Deploy Nginx
