# RestorePoint Demo
# Provision and Deploy a simple HTML web application

trigger: none

pool: Default

variables:
- group: RestorePoint-Demo

stages:
- stage: provisionAKS
  displayName: Provision an AKS cluster
  jobs:
    - job: terraformPlan
      displayName: Terraform Plan for the AKS cluster
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
        displayName: Install Terraform
      
      - task: replacetokens@5
        inputs:
          targetFiles: '**/*.tf'
          encoding: 'auto'
          tokenPattern: 'azpipelines'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true
        displayName: Replace Tokens

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform init
        displayName: Terraform Initialization
      
      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform plan -out=plan.out
        displayName: Terraform Plan
      
      - task: CopyFiles@2
        inputs:
          contents: '$(System.DefaultWorkingDirectory)/Terraform/plan.out'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy Terraform Plan file for later use in the pipeline'

      - publish: '$(Build.ArtifactStagingDirectory)/plan.out'
        artifact: terraformPlan
        displayName: 'Publish Terraform Plan file for later use'

    - job: waitForValidation
      displayName: Manual Validation
      pool: server
      dependsOn: terraformPlan
      steps:   
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: 'abdullah.safi44@gmail.com'
          instructions: 'Please validate the Terraform Plan'
        displayName: Wait for external validation

    - job: terraformApply
      displayName: Provision the AKS cluster
      dependsOn: waitForValidation
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
        displayName: Install Terraform

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'terraformPlan'
          targetPath: '$(System.DefaultWorkingDirectory)/Terraform'

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform init
        displayName: Terraform Initialization

      - script: |
          cd $(System.DefaultWorkingDirectory)/Terraform
          terraform apply plan.out
        displayName: Terraform Apply

- stage: deployApp
  displayName: Deploy Nginx deployment
  dependsOn: provisionAKS
  jobs:
    - job: deploy
      displayName: Deploy Manifest files
      steps:
        - task: KubectlInstaller@0
          inputs:
            kubectlVersion: 'latest'
          displayName: Install Kubectl
        